#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use HavenShen\Slim\Swoole\Commands\HttpServerCommand;

$application = new Application();

// ... register commands
$application->add(new HttpServerCommand());

$application->run();